import type { Payment } from "./types";

export const mockPayments: Payment[] = [
  {
    id: "payment-1",
    clientId: "mock-client-1",
    projectId: "mock-project-1",
    clientName: "Studio Lume",
    projectName: "Landing Page",
    description: "Sinal 50%",
    type: "deposit",
    status: "paid",
    dueDate: "2025-05-20",
    paidAt: "2025-05-20",
    amount: 4100,
  },
  {
    id: "payment-2",
    clientId: "mock-client-1",
    projectId: "mock-project-1",
    clientName: "Studio Lume",
    projectName: "Landing Page",
    description: "Saldo 50%",
    type: "final_payment",
    status: "pending",
    dueDate: "2025-06-05",
    amount: 4100,
  },
  {
    id: "payment-3",
    clientId: "mock-client-2",
    projectId: "mock-project-2",
    clientName: "Vértice",
    projectName: "E-mail Marketing",
    description: "Parcela 1",
    type: "installment",
    status: "pending",
    dueDate: "2025-05-27",
    amount: 1850,
  },
  {
    id: "payment-4",
    clientId: "mock-client-3",
    projectId: "mock-project-3",
    clientName: "Agência Nexo",
    projectName: "Apresentação Institucional",
    description: "Sinal",
    type: "deposit",
    status: "overdue",
    dueDate: "2025-05-15",
    amount: 2750,
  },
  {
    id: "payment-5",
    clientId: "mock-client-4",
    projectId: "mock-project-4",
    clientName: "Brand UP",
    projectName: "Ícones Personalizados",
    description: "Pagamento único",
    type: "extra",
    status: "pending",
    dueDate: "2025-06-10",
    amount: 1200,
  },
  {
    id: "payment-6",
    clientId: "mock-client-5",
    projectId: "mock-project-5",
    clientName: "Loja Integrada",
    projectName: "E-commerce",
    description: "Parcela final",
    type: "final_payment",
    status: "paid",
    dueDate: "2025-05-18",
    paidAt: "2025-05-18",
    amount: 2300,
  },
];
